import{a as c,S as p,i as n}from"./assets/vendor-5401a4b0.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&l(a)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function l(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const m="/goit-js-hw-12/assets/error-icon-945075c7.svg",d=15;let g=1;c.defaults.baseURL="https://pixabay.com/api/";const y="42556248-7d7b04b226b16d9af953a75af";async function h(s){const o=s;return(await c.get("",{params:{page:g,per_page:d,key:y,q:o,image_type:"photo",orientation:"horizontal",safesearch:"true"}})).data}const i={gallery:document.querySelector(".gallery"),formSubmit:document.querySelector(".form"),input:document.querySelector(".input-value"),section:document.querySelector("section"),loader:document.querySelector("div"),loadMoreButton:document.querySelector(".load-more")};function b(s){const o=s.map(({webformatURL:r,largeImageURL:l,tags:e,likes:t,views:a,comments:u,downloads:f})=>`<li class="gallery-item">
                    <a class="gallery-link" href="${l}">
                        <img class="gallery-image"
                            src="${r}" 
                            alt="${e}" />
                    </a>
                    <ul class="list">
                        <li class="list-info">Likes<p class="info">${t}</p></li>
                        <li class="list-info">Views<p class="info">${a}</p></li>
                        <li class="list-info">Comments<p class="info">${u}</p></li>
                        <li class="list-info">Downloads<p class="info">${f}</p></li>
                    </ul>
                </li>`).join("");i.gallery.insertAdjacentHTML("beforeend",o)}const S=new p(".gallery a",{captionsData:"alt",captionDelay:250});i.formSubmit.addEventListener("submit",L);async function L(s){s.preventDefault(),i.gallery.innerHTML="";const o=i.input.value.trim();if(o===""){n.show({titleColor:"#fff",titleSize:"16px",message:"Please, enter your search query!!!",messageColor:"#fff",messageSize:"16px",position:"topRight",backgroundColor:"#59A10D",close:!1});return}i.loader.classList.add("loader");try{const r=await h(o);r.total===0&&n.show({titleColor:"#fff",titleSize:"16px",message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#fff",messageSize:"16px",iconUrl:m,position:"topRight",backgroundColor:"#ef4040",close:!0,maxWidth:"432px"}),b(r.hits),S.refresh()}catch(r){console.log(r)}i.formSubmit.reset()}
//# sourceMappingURL=commonHelpers.js.map
