import{a as d,S as h,i as c}from"./assets/vendor-5401a4b0.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function l(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=l(e);fetch(e.href,o)}})();const L="/goit-js-hw-12/assets/error-icon-945075c7.svg",b=15;d.defaults.baseURL="https://pixabay.com/api/";const S="42556248-7d7b04b226b16d9af953a75af";async function f(r,s){const l=r,{data:a}=await d.get("",{params:{page:s,per_page:b,key:S,q:l,image_type:"photo",orientation:"horizontal",safesearch:"true"}});return a}const t={gallery:document.querySelector(".gallery"),formSubmit:document.querySelector(".form"),input:document.querySelector(".input-value"),section:document.querySelector("section"),loader:document.querySelector("div"),loadMoreButton:document.querySelector('[data-action="load-more"]')};function m(r){const s=r.map(({webformatURL:l,largeImageURL:a,tags:e,likes:o,views:i,comments:g,downloads:y})=>`<li class="gallery-item">
                    <a class="gallery-link" href="${a}">
                        <img class="gallery-image"
                            src="${l}" 
                            alt="${e}" />
                    </a>
                    <ul class="list">
                        <li class="list-info">Likes<p class="info">${o}</p></li>
                        <li class="list-info">Views<p class="info">${i}</p></li>
                        <li class="list-info">Comments<p class="info">${g}</p></li>
                        <li class="list-info">Downloads<p class="info">${y}</p></li>
                    </ul>
                </li>`).join("");t.gallery.insertAdjacentHTML("beforeend",s),t.loader.classList.remove("loader")}const p=new h(".gallery a",{captionsData:"alt",captionDelay:250});let u=1,n;t.loadMoreButton.classList.add("is-close");t.formSubmit.addEventListener("submit",v);async function v(r){if(r.preventDefault(),t.gallery.innerHTML="",t.loadMoreButton.classList.remove("load-more"),n=t.input.value.trim(),t.loadMoreButton.classList.add("is-close"),n===""){c.show({titleColor:"#fff",titleSize:"16px",message:"Please, enter your search query!!!",messageColor:"#fff",messageSize:"16px",position:"topRight",backgroundColor:"#59A10D",close:!1});return}t.loader.classList.add("loader");try{const s=await f(n);if(s.total===0){c.show({titleColor:"#fff",titleSize:"16px",message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#fff",messageSize:"16px",iconUrl:L,position:"topRight",backgroundColor:"#ef4040",close:!0,maxWidth:"432px"}),t.loader.classList.remove("loader");return}m(s.hits),p.refresh()}catch(s){console.log(s)}t.formSubmit.reset(),t.loadMoreButton.classList.remove("is-close")}t.loadMoreButton.addEventListener("click",M);async function M(){u+=1,t.loader.classList.add("loader");try{const r=await f(n,u);if(m(r.hits),p.refresh(),r.hits.length>r.totalHits)return t.loadMoreButton.classList.add("is-close"),c.error({title:"Error",message:"We're sorry, but you've reached the end of search results."})}catch(r){console.log(r)}t.loader.classList.remove("loader")}
//# sourceMappingURL=commonHelpers.js.map
